version: '3.8'

services:
  app:
    build: .
    ports:
      - "8180:8080" # Maps host 8180 to Spring Boot's internal 8080
    volumes:
      - ./data:/app/data
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9190:9090" # Maps host 9190 to Prometheus' internal 9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring
    depends_on:
      - app

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3100:3000" # Maps host 3100 to Grafana's internal 3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - monitoring
    depends_on:
      - prometheus

networks:
  monitoring:
    driver: bridge